version: '3'

services:
  web_app:
    container_name: simple-rest
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "web_app.app:create_app()"
#in production remove --reload option
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
#      - '/d/DEV/WORKSPACE/python/simple-rest-api/web_app:/web_app'
      - '.:/web_app'
    ports:
      - '7000:8000'

